Collect container metrics & use jq to show results

diff --git a/.github/workflows/arch.yml b/.github/workflows/arch.yml
--- a/.github/workflows/arch.yml
+++ b/.github/workflows/arch.yml
@@ -91,6 +91,9 @@ jobs:
       - name: Remove log
         run: |
           rm -fv log
+      - name: Start collecting metrics
+        run: |
+          cd metrics && docker-compose up -d
       - name: Docker
         if: env.TBT_UPDATE_PACKAGE == 'true'
         uses: docker://archlinux:latest
@@ -99,6 +102,21 @@ jobs:
         with:
           entrypoint: /usr/bin/bash
           args: docker/go.sh
+      - name: Show metrics
+        run: |
+          if ! command -v jq &> /dev/null
+          then
+              echo "jq not found! installing ..."
+              sudo apt-get update >dev/null
+              sudo apt-get install -y jq >dev/null
+          fi
+
+          for ((i=1; i<=5; i++)); do
+          sleep 10
+          curl -s 'http://localhost:9090/api/v1/query?query=container_network_receive_bytes_total%7Bimage%3D%22archlinux%3Alatest%22%7D' | \
+              jq 'if (.data.result | length) != 1 then error("Length is not 1!") else (.data.result[0].value[1] | tonumber) end'
+          done
+
       - name: Set commit message
         id: commit_message_step
         if: success() || failure()
