Remove package when metric fails

diff --git a/.github/workflows/arch.yml b/.github/workflows/arch.yml
--- a/.github/workflows/arch.yml
+++ b/.github/workflows/arch.yml
@@ -119,7 +119,12 @@ jobs:
           ./metrics/get-metrics tmp_work_dir/$TBT_PACKAGE_NAME | \
               sudo tee arch/$TBT_PACKAGE_NAME/metrics.json
 
-          ls arch/$TBT_PACKAGE_NAME/metrics.json
+          if [ $? -eq 0 ]; then
+              echo "There were errors when collecting metrics!"
+              sudo rm -rf arch/$TBT_PACKAGE_NAME
+          else
+              ls arch/$TBT_PACKAGE_NAME/metrics.json
+          fi
 
       - name: Remove tmp work dir
         if: success() || failure()
diff --git a/metrics/get-metrics b/metrics/get-metrics
--- a/metrics/get-metrics
+++ b/metrics/get-metrics
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# exit on error
+set -e
+
 if [ -n "$1" ]; then
     cd "$1" || { echo "Failed to change directory"; exit 1; }
 fi
